basepath: /path/to/root
root: depth

town_name: Town10HD
weather: # fixed

task: depth # ss, 2dod, 3dod, depth
split: train # train, val, test, debug. Might add _othertext to obtain additional splits.
billboard: billboard01 # Depends on town!
patch_folder: # folder where to find the patches

patch_type: # Not used
net: # Not used

debug: False





